module.exports = {
    ...require('./startNumberMessage'),
    ...require('./succesRegistration'),
    ...require('./succesRegistrationStiker'),
    ...require('./chooseLanguage'),
    ...require('./chooseWhoAreYou'),
    ...require('./helloArtist'),
    ...require('./helloArtistStiker'),
    ...require('./artistName'),
    ...require('./helloArtistMenu'),
    ...require('./artistMenu'),
    ...require('./artActionsWithPictures'),
    ...require('./artActionsWithPicturesHello'),
    ...require('./artActionsPostPicture'),
    ...require('./artActionsPostPictureImage'),
    ...require('./artActionsPostPictureDescript'),
    ...require('./artActionsPostPictureSize'),
    ...require('./artActionsPostPictureHashtags'),
    ...require('./artActionsPostPictureName'),
    ...require('./artActionsPostPictureDoneText'),
    ...require('./artActionsPostPictureDoneStiker'),
    ...require('./artActionsPostPictureDoneView'),
    ...require('./artActionsPostPictureCreated'),
    ...require('./artActionsPostPictureCreatedMenu'),
    ...require('./artActionsWithoutPicture'),
    
    ...require('./artAdvertising'),
    ...require('./artAdvertisingMore'),
    ...require('./artAdvertisingAllPicturesText'),
    ...require('./artAdvertisingAllPictures'),
    ...require('./artAdvertisingAllPictures'),
    ...require('./artAdvertisingSelectedPicture'),
    ...require('./artAdvertisingPictureButton'),
    ...require('./artViewStatistics'),
    ...require('./artViewStatisticsByHashtags'),
    
    ...require('./changeWhoAreYou'),
    ...require('./changeTypeToBuyer'),
    
    
    ...require('./buyerMenu'),
    ...require('./artDeletePictures'),
    ...require('./artDeletePicturesText'),
    ...require('./artEditDeletePictures'),
    ...require('./artDeleteSelectedPictureButtons'),
    ...require('./artDeleteSelectedPicture'),
    ...require('./artDeleteSelectedPictureStiker'),
    ...require('./artDeleteSelectedPictureText'),
    ...require('./artNotDeleteSelectedPictureStiker'),
    ...require('./artNotDeleteSelectedPictureText'),
    
    ...require('./artEditPictures'),
    ...require('./artEditPicturesText'),
    ...require('./artEditSelectedPicture'),
    ...require('./artEditSelectedPictureButtons'),
    ...require('./artEditEditPictures'),
    ...require('./artEditPictureCategory'),
    ...require('./artEditPictureImage'),
    ...require('./artEditPictureDescription'),
    ...require('./artEditPictureSize'),
    ...require('./artEditPictureHashtags'), 
    ...require('./artEditPictureName'),
    ...require('./artEditPictureCategoryDone'),
    ...require('./artEditPictureImageDone'),
    ...require('./artEditPictureDescriptionDone'),
    ...require('./artEditPictureSizeDone'),
    ...require('./artEditPictureHashtagsDone'),
    ...require('./artEditPictureNameDone'),
    ...require('./artEditSelectedPictureDone'),
    ...require('./artAdvertisingAllPictures'), 
    ...require('./artEditAdvertisingAllPictures'), 

    ...require('./contactWithAdministratorStiker'), 
    ...require('./contactWithAdministrator'), 

    ...require('./helloBuyer'),
    ...require('./helloBuyerStiker'),
    ...require('./buyerMenu'),
    ...require('./buyerSerchPictures'),
    ...require('./buyerSerchPicturesHello'),
    ...require('./buyerSerchPicturesByCategory'),
    ...require('./changeTypeToArtist'),
    ...require('./changeTypeToArtistStiker'),
    
    
    ...require('./buyerSearchPicturesByArtist'),

    ...require('./buyerViewPicture'),
    ...require('./buyerEditViewPicture'),
    ...require('./bayerSearchCategoryId'),

    ...require('./buyerSearchBySizeSetMin'),
    ...require('./buyerSearchBySizeSetMax'),

    ...require('./buyerSearchByHashtag'),

    ...require('./applicationWasSent'),
    ...require('./notificationToAstistAboutApplying'),

    ...require('./advertisingPictureMessage'),
    ...require('./showStatisticByArtist'),
};